### ISSUE TITLE
FastBoot: XMLHttpRequest is not defined

### ISSUE THREAD

**Issue by billdami** [josemarluedke/glimmer-apollo#31]
I am seeing a `XMLHttpRequest is not defined` error from my queries in the fastboot render. Is any additional configuration necessary to get glimmer-apollo working in Fastboot, other than having ember-fetch installed?

I am currently running:

- ember v3.27.5
- ember-cli-fastboot v3.2.0-beta.2 (also tested on v2.2.3)
- ember-fetch v8.1.1
- glimmer-apollo v0.3.0

I can provide additional info if needed, thanks!

**Comment by josemarluedke** [comment]
Humm, yeah. I think what you need to do is set which fetch apollo should use.

Having `ember-fetch` installed, you can import:

```js
import fetch from 'fetch';
```

then in your apollo HTTP link, you can pass the fetch:

```js
  const httpLink = createHttpLink({
    uri: '/api/graphql',
    credentials: 'include',
    fetch
  });
```

Let me know if that works. We should update the docs to include this setup.

**Comment by billdami** [comment]
@josemarluedke yes, looks like that works, thank you!
