### ISSUE TITLE
could we have @glimmer/ depenencies as peer dependencies to avoid package duplication and conflicts?

### ISSUE THREAD

**Issue by lifeart** [josemarluedke/glimmer-apollo#50]
Glimmer allow to have only one @glimmer/validator version in runtime and looks like @glimmer/owner also should be only one to prevent "loosing" ownership.

related issue: https://github.com/josemarluedke/glimmer-apollo/issues/48#issuecomment-946448664

**Comment by josemarluedke** [comment]
Fixed in v0.5.0.
