### ISSUE TITLE
Unable to import schema.graphql using Ember 3.28.4

### ISSUE THREAD

**Issue by xomaczar** [josemarluedke/glimmer-apollo#52]
I am trying to use this addon in an ember app (ember@3.28.4) with ember-auto-import@2.2.3. When I am attempting to import schema.graphql anywhere in the app, it fails with "could not find module". 
Am I missing something

**Comment by josemarluedke** [comment]
I have created a super simple addon that does this:

https://github.com/josemarluedke/ember-cli-graphql-loader

There is no docs, just add it to your project and it should be good to go.
